/**
 * AdaptiveCruiseController.java
 *
 * Generated by Claude Code using the workshop prompt:
 * "Generate a Java class AdaptiveCruiseController that takes radarDist,
 *  v2xSpeedLimit, and isObstacleDetected as inputs. The class should
 *  calculate targetVelocity.
 *  Logic Requirements:
 *  1. If an obstacle is detected, set the velocity to 0.
 *  2. Otherwise, the velocity should match the lower of the current
 *     speed or the V2X speed limit."
 */
public class AdaptiveCruiseController {

    private double currentVelocity;

    public AdaptiveCruiseController() {
        this.currentVelocity = 0.0;
    }

    public double calculateVelocity(double radarDist,
                                    double v2xSpeedLimit,
                                    boolean isObstacleDetected) {
        double targetVelocity;

        if (isObstacleDetected) {
            targetVelocity = 0.0;
        } else {
            targetVelocity = Math.min(radarDist, v2xSpeedLimit);
        }

        this.currentVelocity = targetVelocity;
        return targetVelocity;
    }

    public double getCurrentVelocity() { return currentVelocity; }
}
