/**
 * SensorParser.java
 *
 * Utility class generated by Claude Code to parse raw LiDAR sensor
 * strings into double values for use by AdaptiveCruiseController.
 */
public class SensorParser {

    private double lastValue = 0.0;

    public double parse(String raw) {
        double value = Double.parseDouble(raw);
        lastValue = value;
        return value;
    }

    public double getLastValue() {
        return lastValue;
    }
}
